backend:
  name: git-gateway
  branch: master # or main if that's your default branch

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Buy Price", name: "buyPrice", widget: "number" }
      - { label: "Minimum Sell Price", name: "minimumSellPrice", widget: "number" }
      - { label: "Normal Price", name: "normalPrice", widget: "number" }
      - { label: "Pictures", name: "pictures", widget: "list", field: { label: "Picture", name: "picture", widget: "image" } }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Location", name: "location", widget: "string" }
